development:
        adapter: mysql2
        timeout: 5000
        encoding: utf8
        reconnect: false
        database: my_videos_development
        pool: 100
        username: root
        password: l
        lsocket: /var/run/mysqld/mysqld.sock

test:
        adapter: mysql2
        encoding: utf8
        reconnect: false
        database: my_videos_test
        pool: 100
        username: root
        password: l
        socket: /var/run/mysqld/mysqld.sock

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: my_videos_production
  username: my_videos
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
